CREATE TABLE poll_users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999,
  name varchar2(40) NOT NULL,
  username varchar2(15) NOT NULL,
  email varchar2(40) NOT NULL,
  password varchar2(100) NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT poll_users_id_PK PRIMARY KEY (user_id),
  CONSTRAINT poll_users_username_unique UNIQUE (username),
  CONSTRAINT poll_users_email_unique UNIQUE (email)
);
SELECT * FROM poll_users;

CREATE TABLE poll_roles (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999,
  name varchar2(60) NOT NULL,
  CONSTRAINT poll_roles_id_PK PRIMARY KEY (role_id),
  CONSTRAINT poll_roles_name_unique UNIQUE (name)
);
SELECT * FROM poll_roles;

CREATE TABLE poll_user_roles (
  user_id NUMBER,
  role_id NUMBER,
  CONSTRAINT poll_user_roles_id_pk PRIMARY KEY (user_id,role_id),
 -- KEY fk_user_roles_role_id (role_id),
  CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES poll_roles (role_id),
  CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES poll_users (user_id)
);
SELECT * FROM poll_user_roles;

CREATE TABLE polls (
  polls_id NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999,
  question varchar2(140) NOT NULL,
  expiration_date_time date NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  created_by int ,
  updated_by int ,
  CONSTRAINT polls_id_PK PRIMARY KEY (polls_id)
);
SELECT * FROM polls;

CREATE TABLE choices (
  choices_id NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999,
  text varchar2(40) NOT NULL,
  poll_id int,
  CONSTRAINT choices_id_PK PRIMARY KEY (choices_id),
  --PRIMARY KEY (id),
  --KEY fk_choices_poll_id (poll_id),
  CONSTRAINT fk_choices_poll_id FOREIGN KEY (poll_id) REFERENCES polls (polls_id)
);
SELECT * FROM choices;

CREATE TABLE votes (
  votes_id NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999,
  user_id int,
  poll_id int,
  choice_id int,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT votes_id_PK PRIMARY KEY (votes_id),
  --KEY fk_votes_user_id (user_id),
  --KEY fk_votes_poll_id (poll_id),
  --KEY fk_votes_choice_id (choice_id),
  CONSTRAINT fk_votes_user_id FOREIGN KEY (user_id) REFERENCES users (user_id),
  CONSTRAINT fk_votes_poll_id FOREIGN KEY (poll_id) REFERENCES polls (polls_id),
  CONSTRAINT fk_votes_choice_id FOREIGN KEY (choice_id) REFERENCES choices (choices_id)
);
SELECT * FROM votes;
