CREATE TABLE poll_users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999,
  name varchar2(40) NOT NULL,
  username varchar2(15) NOT NULL,
  email varchar2(40) NOT NULL,
  password varchar2(100) NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT poll_users_id_PK PRIMARY KEY (user_id),
  CONSTRAINT poll_users_username_unique UNIQUE (username),
  CONSTRAINT poll_users_email_unique UNIQUE (email)
);

SELECT * FROM poll_users;

CREATE TABLE poll_roles (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999,
  name varchar2(60) NOT NULL,
  CONSTRAINT "poll_roles_PK" PRIMARY KEY ("role_id"),
  CONSTRAINT poll_roles_name_unique UNIQUE (name)
);


CREATE TABLE user_roles (
  user_id bigint(20) NOT NULL,
  role_id bigint(20) NOT NULL,
  PRIMARY KEY (user_id,role_id),
  KEY fk_user_roles_role_id (role_id),
  CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id),
  CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (id)
)


CREATE TABLE polls (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  question varchar(140) NOT NULL,
  expiration_date_time datetime NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  created_by bigint(20) DEFAULT NULL,
  updated_by bigint(20) DEFAULT NULL,
  PRIMARY KEY (id)
)


CREATE TABLE choices (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  text varchar(40) NOT NULL,
  poll_id bigint(20) NOT NULL,
  PRIMARY KEY (id),
  KEY fk_choices_poll_id (poll_id),
  CONSTRAINT fk_choices_poll_id FOREIGN KEY (poll_id) REFERENCES polls (id)
)


CREATE TABLE votes (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  user_id bigint(20) NOT NULL,
  poll_id bigint(20) NOT NULL,
  choice_id bigint(20) NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY fk_votes_user_id (user_id),
  KEY fk_votes_poll_id (poll_id),
  KEY fk_votes_choice_id (choice_id),
  CONSTRAINT fk_votes_user_id FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_votes_poll_id FOREIGN KEY (poll_id) REFERENCES polls (id),
  CONSTRAINT fk_votes_choice_id FOREIGN KEY (choice_id) REFERENCES choices (id)
)
